version: '3.8'

services:
  api:
    build: api
    container_name: url_redis_api
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    build: db
    container_name: redis_db
    ports:
      - "6379:6379"
    volumes:
      - .data:/data
