version: '3.8'

services:
  db:
    image: redis:6.2-alpine
    container_name: urlredis-database
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --loglevel warning 
    volumes: 
      - data:/data
    networks:
      - url-redis
 
 
  api:
    build: api
    container_name: urlredis-api
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - url-redis    
volumes:
  data:
  
networks:
  url-redis:
    driver: bridge
